SET INPUT_DIRECTORY="./"
SET OUTPUT_DIRECTORY="./output/"
SET NUM_THREADS=0
SET PIC_SCALE=0.9
SET WHITE_THRESHOLD=230
SET PHOTOS_PER_SCAN=1
SET BLUR_AMOUNT=9

python scan_cropper.py -d %INPUT_DIRECTORY% -o %OUTPUT_DIRECTORY% -n %NUM_THREADS%^
 -s %PIC_SCALE% -t %WHITE_THRESHOLD% -i %PHOTOS_PER_SCAN% -b %BLUR_AMOUNT%

pause